export const CARE_PLANS = [
  {
    id: "basic-care",
    name: "Basic Care Plan",
    price: 4999,
    discountedPrice: 3999,
    discount: "20% OFF",
    category: "Basic",
    duration: "3 months",
    rating: 4.2,
    features: {
      coaches: 1,
      nutritionists: 1,
      nutraceuticals: 2,
      devices: ["Fitness Tracker"],
      coachSessions: 8,
      nutritionistSessions: 6,
      mentalHealthSessions: 4,
    },
    description: "Essential care with basic coaching and nutrition support",
    popular: false,
  },
  {
    id: "enhanced-care",
    name: "Enhanced Care Plan",
    price: 8999,
    discountedPrice: 6999,
    discount: "22% OFF",
    category: "Enhanced",
    duration: "6 months",
    rating: 4.6,
    features: {
      coaches: 2,
      nutritionists: 1,
      nutraceuticals: 4,
      devices: ["Smart Watch", "BCA Scale"],
      coachSessions: 16,
      nutritionistSessions: 12,
      mentalHealthSessions: 8,
    },
    description: "Comprehensive care with enhanced monitoring and support",
    popular: true,
  },
  {
    id: "premium-care",
    name: "Premium Care Plan",
    price: 14999,
    discountedPrice: 11999,
    discount: "20% OFF",
    category: "Premium",
    duration: "12 months",
    rating: 4.8,
    features: {
      coaches: 3,
      nutritionists: 2,
      nutraceuticals: 6,
      devices: ["Smart Watch", "BCA Scale", "Blood Pressure Monitor"],
      coachSessions: 24,
      nutritionistSessions: 18,
      mentalHealthSessions: 12,
    },
    description: "Complete premium care with dedicated team and advanced monitoring",
    popular: false,
  },
  {
    id: "family-care",
    name: "Family Care Plan",
    price: 19999,
    discountedPrice: 15999,
    discount: "20% OFF",
    category: "Family",
    duration: "12 months",
    rating: 4.7,
    features: {
      coaches: 2,
      nutritionists: 2,
      nutraceuticals: 8,
      devices: ["2x Smart Watch", "2x BCA Scale"],
      coachSessions: 32,
      nutritionistSessions: 24,
      mentalHealthSessions: 16,
    },
    description: "Comprehensive care plan designed for families up to 4 members",
    popular: false,
  },
  {
    id: "senior-care",
    name: "Senior Care Plan",
    price: 12999,
    discountedPrice: 9999,
    discount: "23% OFF",
    category: "Senior",
    duration: "6 months",
    rating: 4.5,
    features: {
      coaches: 2,
      nutritionists: 1,
      nutraceuticals: 5,
      devices: ["Health Monitor", "Emergency Alert"],
      coachSessions: 20,
      nutritionistSessions: 15,
      mentalHealthSessions: 10,
    },
    description: "Specialized care plan tailored for senior health needs",
    popular: false,
  },
  {
    id: "recovery-care",
    name: "Recovery Care Plan",
    price: 16999,
    discountedPrice: 13999,
    discount: "18% OFF",
    category: "Recovery",
    duration: "9 months",
    rating: 4.9,
    features: {
      coaches: 3,
      nutritionists: 2,
      nutraceuticals: 7,
      devices: ["Recovery Tracker", "Sleep Monitor", "BCA Scale"],
      coachSessions: 28,
      nutritionistSessions: 20,
      mentalHealthSessions: 15,
    },
    description: "Intensive recovery-focused care with specialized support",
    popular: false,
  },
]
