export const SPECIALISTS = [
  {
    name: "Dr. Ananya Iyer",
    role: "Gynaecologist",
    avatar: "/placeholder.svg?height=60&width=60",
    price: 600,
    experience: "12+ years",
  },
  {
    name: "Dr. Meera Krishnan",
    role: "Menopause Specialist",
    avatar: "/placeholder.svg?height=60&width=60",
    price: 800,
    experience: "15+ years",
  },
  {
    name: "Priya Nair",
    role: "Nurse Educator",
    avatar: "/placeholder.svg?height=60&width=60",
    price: 300,
    experience: "8+ years",
  },
  {
    name: "Sneha Deshpande",
    role: "Women's Health Coach",
    avatar: "/placeholder.svg?height=60&width=60",
    price: 350,
    experience: "6+ years",
  },
]

export const TREATMENT_CYCLES = [
  {
    id: "cycle-3",
    cycleNumber: 3,
    status: "Upcoming" as const,
    scheduledDate: "January 15, 2025",
    targetTherapyDrug: "Prescribed Treatment",
    therapyType: "Women's Health Program",
    deliveryStatus: {
      ordered: true,
      shipped: false,
      delivered: false,
      deliveryAddress: "123 Main Street, Apartment 4B, Mumbai, Maharashtra 400001",
    },
  },
  {
    id: "cycle-2",
    cycleNumber: 2,
    status: "Complete" as const,
    completedDate: "December 18, 2024",
    targetTherapyDrug: "Prescribed Treatment",
    therapyType: "Women's Health Program",
    deliveryStatus: {
      ordered: true,
      shipped: true,
      delivered: true,
      deliveryAddress: "123 Main Street, Apartment 4B, Mumbai, Maharashtra 400001",
    },
  },
  {
    id: "cycle-1",
    cycleNumber: 1,
    status: "Complete" as const,
    completedDate: "November 20, 2024",
    targetTherapyDrug: "Prescribed Treatment",
    therapyType: "Women's Health Program",
    deliveryStatus: {
      ordered: true,
      shipped: true,
      delivered: true,
      deliveryAddress: "123 Main Street, Apartment 4B, Mumbai, Maharashtra 400001",
    },
  },
]

export const EDUCATIONAL_CONTENT = [
  {
    title: "Understanding Your Cycle Phases",
    tags: ["Basics", "Cycle"],
    image: "/placeholder.svg?height=80&width=120&text=Cycle",
    duration: "8 min read",
    category: "Your Cycle",
  },
  {
    title: "Perimenopause: What's Changing & Why",
    tags: ["Perimenopause", "Basics"],
    image: "/placeholder.svg?height=80&width=120&text=Perimenopause",
    duration: "10 min read",
    category: "Perimenopause & Menopause",
  },
  {
    title: "Hormone Therapy, Explained",
    tags: ["HRT", "Basics"],
    image: "/placeholder.svg?height=80&width=120&text=HRT",
    duration: "8 min read",
    category: "Hormone Therapy",
  },
  {
    title: "Why Daily Symptom Logs Matter",
    tags: ["Logging", "Self-Care"],
    image: "/placeholder.svg?height=80&width=120&text=Logging",
    duration: "6 min read",
    category: "Symptoms & Tracking",
  },
  {
    title: "Bone & Heart Health After Menopause",
    tags: ["Bone Health", "Heart"],
    image: "/placeholder.svg?height=80&width=120&text=BoneHeart",
    duration: "10 min read",
    category: "Lifestyle & Wellbeing",
  },
  {
    title: "Sleep, Mood & Hormones",
    tags: ["Sleep", "Mood"],
    image: "/placeholder.svg?height=80&width=120&text=SleepMood",
    duration: "9 min read",
    category: "Symptoms & Tracking",
  },
]

export const LAB_TESTS = [
  {
    name: "Liver Function Test",
    price: 899,
    discountedPrice: 699,
    discount: "22% OFF",
    category: "Blood Tests",
    fasting: true,
  },
  { name: "Hormone Panel", price: 450, discountedPrice: 350, discount: "22% OFF", category: "Women's Health", fasting: false },
  { name: "CBC", price: 300, discountedPrice: 250, discount: "17% OFF", category: "Blood Tests", fasting: false },
  {
    name: "Kidney Function",
    price: 550,
    discountedPrice: 450,
    discount: "18% OFF",
    category: "Blood Tests",
    fasting: true,
  },
  {
    name: "Thyroid Profile",
    price: 600,
    discountedPrice: 480,
    discount: "20% OFF",
    category: "Hormones",
    fasting: false,
  },
  {
    name: "Lipid Profile",
    price: 400,
    discountedPrice: 320,
    discount: "20% OFF",
    category: "Heart Health",
    fasting: true,
  },
  { name: "Vitamin D", price: 800, discountedPrice: 640, discount: "20% OFF", category: "Vitamins", fasting: false },
  {
    name: "Iron Studies",
    price: 700,
    discountedPrice: 560,
    discount: "20% OFF",
    category: "Blood Tests",
    fasting: true,
  },
]

export const CARE_PRODUCTS = [
  {
    name: "Hair Wigs",
    price: 2999,
    discountedPrice: 2499,
    discount: "17% OFF",
    category: "Personal Care",
    rating: 4.5,
  },
  {
    name: "Cancer Care Kit",
    price: 1899,
    discountedPrice: 1599,
    discount: "16% OFF",
    category: "Medical Supplies",
    rating: 4.8,
  },
  {
    name: "Prosthesis",
    price: 4999,
    discountedPrice: 4299,
    discount: "14% OFF",
    category: "Medical Devices",
    rating: 4.3,
  },
  { name: "Mobility Aids", price: 3500, discountedPrice: 2999, discount: "14% OFF", category: "Mobility", rating: 4.6 },
  {
    name: "Compression Garments",
    price: 1200,
    discountedPrice: 999,
    discount: "17% OFF",
    category: "Medical Supplies",
    rating: 4.4,
  },
  { name: "Wheelchair", price: 8999, discountedPrice: 7499, discount: "17% OFF", category: "Mobility", rating: 4.7 },
  {
    name: "Hospital Bed",
    price: 15999,
    discountedPrice: 13499,
    discount: "16% OFF",
    category: "Medical Equipment",
    rating: 4.5,
  },
  {
    name: "Oxygen Concentrator",
    price: 25999,
    discountedPrice: 21999,
    discount: "15% OFF",
    category: "Medical Equipment",
    rating: 4.8,
  },
]

export const LAB_REPORTS = [
  {
    id: "report-1",
    name: "Complete Blood Count (CBC)",
    date: "2024-12-15",
    time: "10:30 AM",
    status: "Normal" as const,
    category: "Blood Tests",
    summary: "All blood parameters are within normal range. Hemoglobin levels show improvement from previous test.",
    recommendations: [
      "Continue current iron supplementation",
      "Maintain balanced diet rich in leafy greens",
      "Schedule follow-up in 3 months",
    ],
    results: [
      {
        parameter: "Hemoglobin",
        value: "13.2",
        unit: "g/dL",
        range: "12.0-15.5",
        status: "Normal" as const,
        trend: "up" as const,
      },
      {
        parameter: "White Blood Cells",
        value: "7.2",
        unit: "×10³/μL",
        range: "4.0-11.0",
        status: "Normal" as const,
        trend: "stable" as const,
      },
      {
        parameter: "Platelets",
        value: "285",
        unit: "×10³/μL",
        range: "150-450",
        status: "Normal" as const,
        trend: "stable" as const,
      },
      {
        parameter: "Hematocrit",
        value: "39.8",
        unit: "%",
        range: "36.0-46.0",
        status: "Normal" as const,
        trend: "up" as const,
      },
    ],
  },
  {
    id: "report-2",
    name: "Lipid Profile",
    date: "2024-12-10",
    time: "9:15 AM",
    status: "Good" as const,
    category: "Heart Health",
    summary: "Significant improvement in cholesterol levels. Total cholesterol reduced by 23% from previous test.",
    recommendations: [
      "Continue current exercise routine",
      "Maintain low-saturated fat diet",
      "Consider omega-3 supplements",
    ],
    results: [
      {
        parameter: "Total Cholesterol",
        value: "220",
        unit: "mg/dL",
        range: "<200",
        status: "High" as const,
        trend: "down" as const,
      },
      {
        parameter: "HDL Cholesterol",
        value: "58",
        unit: "mg/dL",
        range: ">40",
        status: "Normal" as const,
        trend: "up" as const,
      },
      {
        parameter: "LDL Cholesterol",
        value: "142",
        unit: "mg/dL",
        range: "<100",
        status: "High" as const,
        trend: "down" as const,
      },
      {
        parameter: "Triglycerides",
        value: "98",
        unit: "mg/dL",
        range: "<150",
        status: "Normal" as const,
        trend: "stable" as const,
      },
    ],
  },
  {
    id: "report-3",
    name: "Liver Function Test",
    date: "2024-12-08",
    time: "11:45 AM",
    status: "Normal" as const,
    category: "Liver Health",
    summary: "All liver function parameters are within normal limits. No signs of liver stress or damage.",
    recommendations: [
      "Continue current medication regimen",
      "Maintain adequate hydration",
      "Limit alcohol consumption",
    ],
    results: [
      {
        parameter: "ALT",
        value: "28",
        unit: "U/L",
        range: "7-56",
        status: "Normal" as const,
        trend: "stable" as const,
      },
      {
        parameter: "AST",
        value: "32",
        unit: "U/L",
        range: "10-40",
        status: "Normal" as const,
        trend: "stable" as const,
      },
      {
        parameter: "Bilirubin Total",
        value: "0.8",
        unit: "mg/dL",
        range: "0.3-1.2",
        status: "Normal" as const,
        trend: "stable" as const,
      },
      {
        parameter: "Albumin",
        value: "4.2",
        unit: "g/dL",
        range: "3.5-5.0",
        status: "Normal" as const,
        trend: "stable" as const,
      },
    ],
  },
  {
    id: "report-4",
    name: "Complete Blood Count (CBC)",
    date: "2024-11-20",
    time: "2:30 PM",
    status: "Good" as const,
    category: "Blood Tests",
    summary: "Previous CBC results showing steady improvement in blood parameters.",
    results: [
      {
        parameter: "Hemoglobin",
        value: "12.8",
        unit: "g/dL",
        range: "12.0-15.5",
        status: "Normal" as const,
        trend: "stable" as const,
      },
      {
        parameter: "White Blood Cells",
        value: "6.8",
        unit: "×10³/μL",
        range: "4.0-11.0",
        status: "Normal" as const,
        trend: "stable" as const,
      },
      {
        parameter: "Platelets",
        value: "290",
        unit: "×10³/μL",
        range: "150-450",
        status: "Normal" as const,
        trend: "stable" as const,
      },
      {
        parameter: "Hematocrit",
        value: "38.5",
        unit: "%",
        range: "36.0-46.0",
        status: "Normal" as const,
        trend: "stable" as const,
      },
    ],
  },
  {
    id: "report-5",
    name: "Lipid Profile",
    date: "2024-11-15",
    time: "8:00 AM",
    status: "Needs Attention" as const,
    category: "Heart Health",
    summary: "Previous lipid profile showing elevated cholesterol levels before lifestyle modifications.",
    results: [
      {
        parameter: "Total Cholesterol",
        value: "285",
        unit: "mg/dL",
        range: "<200",
        status: "High" as const,
        trend: "stable" as const,
      },
      {
        parameter: "HDL Cholesterol",
        value: "45",
        unit: "mg/dL",
        range: ">40",
        status: "Normal" as const,
        trend: "stable" as const,
      },
      {
        parameter: "LDL Cholesterol",
        value: "195",
        unit: "mg/dL",
        range: "<100",
        status: "High" as const,
        trend: "stable" as const,
      },
      {
        parameter: "Triglycerides",
        value: "225",
        unit: "mg/dL",
        range: "<150",
        status: "High" as const,
        trend: "stable" as const,
      },
    ],
  },
]
