import { Truck, Pill, FileText, CheckCircle2, Video, BookOpen } from "lucide-react"

export const NOTIFICATION_TYPES = {
  CYCLE: "cycle",
  DELIVERY: "delivery",
  OTP: "otp",
  MEDICATION: "medication",
  DOCUMENT: "document",
  APPROVAL: "approval",
  VIDEO_UPLOAD: "video_upload",
  ARTICLE_PUBLISHED: "article_published",
} as const

export const INITIAL_NOTIFICATIONS = [
  {
    id: 1,
    title: "Medication Reminder",
    message: "Time to take your morning medication - Glucosamine 500mg",
    type: NOTIFICATION_TYPES.MEDICATION,
    isRead: false,
    timestamp: "10 minutes ago",
    icon: Pill,
    color: "text-green-600",
    bgColor: "bg-green-50",
  },
  {
    id: 2,
    title: "Upload Recovery Video",
    message: "Please upload your daily recovery exercise video for today",
    type: NOTIFICATION_TYPES.VIDEO_UPLOAD,
    isRead: false,
    timestamp: "2 hours ago",
    icon: Video,
    color: "text-purple-600",
    bgColor: "bg-purple-50",
  },
  {
    id: 3,
    title: "New Article Published",
    message: "Check out: 'Managing Joint Pain Through Diet and Exercise'",
    type: NOTIFICATION_TYPES.ARTICLE_PUBLISHED,
    isRead: false,
    timestamp: "4 hours ago",
    icon: BookOpen,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
  },
  {
    id: 4,
    title: "Document Required",
    message: "Please upload your latest X-ray report for review",
    type: NOTIFICATION_TYPES.DOCUMENT,
    isRead: false,
    timestamp: "6 hours ago",
    icon: FileText,
    color: "text-red-600",
    bgColor: "bg-red-50",
  },
  {
    id: 5,
    title: "Document Approved",
    message: "Your MRI scan has been reviewed and approved by Dr. Smith",
    type: NOTIFICATION_TYPES.APPROVAL,
    isRead: true,
    timestamp: "1 day ago",
    icon: CheckCircle2,
    color: "text-green-600",
    bgColor: "bg-green-50",
  },
  {
    id: 6,
    title: "Medication Delivery",
    message: "Your monthly medication package will arrive tomorrow",
    type: NOTIFICATION_TYPES.DELIVERY,
    isRead: true,
    timestamp: "1 day ago",
    icon: Truck,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
  },
  {
    id: 7,
    title: "Evening Medication",
    message: "Don't forget your evening dose - Ibuprofen 400mg",
    type: NOTIFICATION_TYPES.MEDICATION,
    isRead: true,
    timestamp: "2 days ago",
    icon: Pill,
    color: "text-green-600",
    bgColor: "bg-green-50",
  },
  {
    id: 8,
    title: "New Article Published",
    message: "Read: 'Post-Surgery Recovery: What to Expect in Week 1'",
    type: NOTIFICATION_TYPES.ARTICLE_PUBLISHED,
    isRead: true,
    timestamp: "3 days ago",
    icon: BookOpen,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
  },
  {
    id: 9,
    title: "Lab Results Available",
    message: "Your blood test results are ready for review",
    type: NOTIFICATION_TYPES.DOCUMENT,
    isRead: true,
    timestamp: "4 days ago",
    icon: FileText,
    color: "text-orange-600",
    bgColor: "bg-orange-50",
  },
  {
    id: 10,
    title: "Recovery Video Uploaded",
    message: "Your exercise video has been successfully uploaded and is under review",
    type: NOTIFICATION_TYPES.APPROVAL,
    isRead: true,
    timestamp: "5 days ago",
    icon: CheckCircle2,
    color: "text-green-600",
    bgColor: "bg-green-50",
  },
]
